-- MySQL Script generated by MySQL Workbench
-- Mon May 18 12:55:58 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kawi_agung` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema weshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema weshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kawi_agung` DEFAULT CHARACTER SET utf8mb4 ;
USE `kawi_agung` ;

-- -----------------------------------------------------
-- Table `weshop`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kawi_agung`.`user` (
  `user_id` INT(10) NOT NULL AUTO_INCREMENT,
  `nama` VARCHAR(150) NOT NULL,
  `email` VARCHAR(160) NOT NULL,
  `alamat` VARCHAR(400) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `password` VARCHAR(300) NOT NULL,
  `status` ENUM('on', 'off') NOT NULL,
  `jenis_user` ENUM('superadmin', 'admin', 'pengiriman', 'pelanggan') NULL,
  `kota` VARCHAR(45) NULL,
  `provinsi` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`surat_jalan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kawi_agung`.`surat_jalan` (
  `no_surat_jalan` INT NOT NULL,
  `tanggal` DATE NULL,
  `alamat` VARCHAR(45) NULL,
  `user_user_id` INT(10) NOT NULL,
  PRIMARY KEY (`no_surat_jalan`),
  INDEX `fk_surat_jalan_user_idx` (`user_user_id` ASC),
  CONSTRAINT `fk_surat_jalan_user`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `kawi_agung`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weshop`.`kategori`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kawi_agung`.`kategori` (
  `kategori_id` INT(10) NOT NULL AUTO_INCREMENT,
  `kategori` VARCHAR(150) NOT NULL,
  `status` ENUM('on', 'off') NOT NULL,
  PRIMARY KEY (`kategori_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`merk`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kawi_agung`.`merk` (
  `merk_id` INT NOT NULL AUTO_INCREMENT,
  `nama` VARCHAR(45) NULL,
  `status` ENUM('on', 'off') NULL,
  PRIMARY KEY (`merk_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weshop`.`barang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kawi_agung`.`barang` (
  `barang_id` INT(10) NOT NULL AUTO_INCREMENT,
  `kategori_id` INT(10) NOT NULL,
  `nama_barang` VARCHAR(250) NOT NULL,
  `gambar` VARCHAR(300) NOT NULL,
  `harga_jual` INT(10) NOT NULL,
  `harga_beli` INT(10) NULL,
  `stok` TINYINT(2) NOT NULL,
  `stok_minimal` TINYINT(2) NULL,
  `status` ENUM('on', 'off') NOT NULL,
  `deskripsi` TEXT NULL,
  `berat` VARCHAR(45) NULL,
  `diskon_persen` INT(2) NULL,
  `merk_idmerk` INT NOT NULL,
  PRIMARY KEY (`barang_id`),
  INDEX `kategori_id` (`kategori_id` ASC),
  INDEX `fk_barang_merk1_idx` (`merk_idmerk` ASC),
  CONSTRAINT `barang_ibfk_1`
    FOREIGN KEY (`kategori_id`)
    REFERENCES `kawi_agung`.`kategori` (`kategori_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_barang_merk1`
    FOREIGN KEY (`merk_idmerk`)
    REFERENCES `kawi_agung`.`merk` (`merk_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`surat_jalan_has_barang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kawi_agung`.`surat_jalan_has_barang` (
  `surat_jalan_no_surat_jalan` INT NOT NULL,
  `barang_barang_id` INT(10) NOT NULL,
  `quantity` INT(5) NULL,
  `stok` VARCHAR(30) NULL,
  PRIMARY KEY (`surat_jalan_no_surat_jalan`, `barang_barang_id`),
  INDEX `fk_surat_jalan_has_barang_barang1_idx` (`barang_barang_id` ASC),
  INDEX `fk_surat_jalan_has_barang_surat_jalan1_idx` (`surat_jalan_no_surat_jalan` ASC),
  CONSTRAINT `fk_surat_jalan_has_barang_surat_jalan1`
    FOREIGN KEY (`surat_jalan_no_surat_jalan`)
    REFERENCES `kawi_agung`.`surat_jalan` (`no_surat_jalan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_surat_jalan_has_barang_barang1`
    FOREIGN KEY (`barang_barang_id`)
    REFERENCES `kawi_agung`.`barang` (`barang_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`nota_penjualan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kawi_agung`.`nota_penjualan` (
  `nomor_nota_jual` INT NOT NULL,
  `rekening_bank` VARCHAR(45) NULL,
  `tanggal` DATE NULL,
  PRIMARY KEY (`nomor_nota_jual`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`nota_penjualan_has_barang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kawi_agung`.`nota_penjualan_has_barang` (
  `nota_penjualan_nomor_nota_jual` INT NOT NULL,
  `barang_barang_id` INT(10) NOT NULL,
  `qty` INT(15) NULL,
  `total_harga` INT(15) NULL,
  `user_user_id` INT(10) NOT NULL,
  `sub_total` INT(12) NULL,
  `satuan` INT(10) NULL,
  PRIMARY KEY (`nota_penjualan_nomor_nota_jual`, `barang_barang_id`),
  INDEX `fk_nota_penjualan_has_barang_barang1_idx` (`barang_barang_id` ASC),
  INDEX `fk_nota_penjualan_has_barang_nota_penjualan1_idx` (`nota_penjualan_nomor_nota_jual` ASC),
  INDEX `fk_nota_penjualan_has_barang_user1_idx` (`user_user_id` ASC),
  CONSTRAINT `fk_nota_penjualan_has_barang_nota_penjualan1`
    FOREIGN KEY (`nota_penjualan_nomor_nota_jual`)
    REFERENCES `kawi_agung`.`nota_penjualan` (`nomor_nota_jual`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nota_penjualan_has_barang_barang1`
    FOREIGN KEY (`barang_barang_id`)
    REFERENCES `kawi_agung`.`barang` (`barang_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nota_penjualan_has_barang_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `kawi_agung`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kawi_agung`.`supplier` (
  `idsupplier` INT NOT NULL AUTO_INCREMENT,
  `nama` VARCHAR(70) NULL,
  `alamat` VARCHAR(400) NULL,
  `phone` VARCHAR(15) NULL,
  PRIMARY KEY (`idsupplier`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`nota_pembelian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kawi_agung`.`nota_pembelian` (
  `nomor_nota_beli` INT NOT NULL,
  `tanggal` DATE NULL,
  `supplier_idsupplier` INT NOT NULL,
  PRIMARY KEY (`nomor_nota_beli`),
  INDEX `fk_nota_pembelian_supplier1_idx` (`supplier_idsupplier` ASC),
  CONSTRAINT `fk_nota_pembelian_supplier1`
    FOREIGN KEY (`supplier_idsupplier`)
    REFERENCES `kawi_agung`.`supplier` (`idsupplier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`nota_pembelian_has_barang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kawi_agung`.`nota_pembelian_has_barang` (
  `nota_pembelian_nomor_nota_beli` INT NOT NULL,
  `barang_barang_id` INT(10) NOT NULL,
  `quantity` INT(4) NULL,
  `jumlah` INT(15) NULL,
  `sub_total` INT(15) NULL,
  PRIMARY KEY (`nota_pembelian_nomor_nota_beli`, `barang_barang_id`),
  INDEX `fk_nota_pembelian_has_barang_barang1_idx` (`barang_barang_id` ASC),
  INDEX `fk_nota_pembelian_has_barang_nota_pembelian1_idx` (`nota_pembelian_nomor_nota_beli` ASC),
  CONSTRAINT `fk_nota_pembelian_has_barang_nota_pembelian1`
    FOREIGN KEY (`nota_pembelian_nomor_nota_beli`)
    REFERENCES `kawi_agung`.`nota_pembelian` (`nomor_nota_beli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nota_pembelian_has_barang_barang1`
    FOREIGN KEY (`barang_barang_id`)
    REFERENCES `kawi_agung`.`barang` (`barang_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`supplier_has_barang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kawi_agung`.`supplier_has_barang` (
  `supplier_idsupplier` INT NOT NULL,
  `barang_barang_id` INT(10) NOT NULL,
  PRIMARY KEY (`supplier_idsupplier`, `barang_barang_id`),
  INDEX `fk_supplier_has_barang_barang1_idx` (`barang_barang_id` ASC),
  INDEX `fk_supplier_has_barang_supplier1_idx` (`supplier_idsupplier` ASC),
  CONSTRAINT `fk_supplier_has_barang_supplier1`
    FOREIGN KEY (`supplier_idsupplier`)
    REFERENCES `kawi_agung`.`supplier` (`idsupplier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_supplier_has_barang_barang1`
    FOREIGN KEY (`barang_barang_id`)
    REFERENCES `kawi_agung`.`barang` (`barang_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `kawi_agung` ;

-- -----------------------------------------------------
-- Table `weshop`.`pengiriman`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kawi_agung`.`pengiriman` (
  `pengiriman_id` INT(10) NOT NULL AUTO_INCREMENT,
  `kota_tujuan` VARCHAR(150) NOT NULL,
  `tarif` INT(10) NOT NULL,
  `status` ENUM('on', 'off') NOT NULL,
  `nomor_resi` VARCHAR(45) NULL,
  `pengirim` VARCHAR(45) NULL,
  PRIMARY KEY (`pengiriman_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `weshop`.`pesanan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kawi_agung`.`pesanan` (
  `pesanan_id` INT(10) NOT NULL AUTO_INCREMENT,
  `pengiriman_id` INT(10) NOT NULL,
  `user_id` INT(10) NOT NULL,
  `nama_penerima` VARCHAR(150) NOT NULL,
  `nomor_telepon` VARCHAR(15) NOT NULL,
  `alamat` VARCHAR(300) NOT NULL,
  `tanggal_pemesanan` DATETIME NOT NULL,
  `status` ENUM('on', 'off') NOT NULL,
  `lokasi` VARCHAR(45) NULL,
  PRIMARY KEY (`pesanan_id`),
  INDEX `kota_id` (`pengiriman_id` ASC),
  INDEX `user_id` (`user_id` ASC),
  CONSTRAINT `pesanan_ibfk_1`
    FOREIGN KEY (`pengiriman_id`)
    REFERENCES `kawi_agung`.`pengiriman` (`pengiriman_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `pesanan_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `kawi_agung`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `weshop`.`konfirmasi_pembayaran`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kawi_agung`.`konfirmasi_pembayaran` (
  `konfirmasi_id` INT(10) NOT NULL,
  `pesanan_id` INT(10) NOT NULL,
  `nomor_rekening` VARCHAR(20) NOT NULL,
  `nama_account` VARCHAR(150) NOT NULL,
  `tanggal_transfer` DATE NOT NULL,
  `foto_bukti` VARCHAR(90) NULL,
  PRIMARY KEY (`konfirmasi_id`),
  INDEX `pesanan_id` (`pesanan_id` ASC),
  CONSTRAINT `konfirmasi_pembayaran_ibfk_1`
    FOREIGN KEY (`pesanan_id`)
    REFERENCES `kawi_agung`.`pesanan` (`pesanan_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `weshop`.`pesanan_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kawi_agung`.`pesanan_detail` (
  `pesanan_id` INT(10) NOT NULL,
  `barang_id` INT(10) NOT NULL,
  `quantity` TINYINT(2) NOT NULL,
  `harga` INT(10) NOT NULL,
  INDEX `pesanan_id` (`pesanan_id` ASC),
  INDEX `barang_id` (`barang_id` ASC),
  CONSTRAINT `pesanan_detail_ibfk_1`
    FOREIGN KEY (`pesanan_id`)
    REFERENCES `kawi_agung`.`pesanan` (`pesanan_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `pesanan_detail_ibfk_2`
    FOREIGN KEY (`barang_id`)
    REFERENCES `kawi_agung`.`barang` (`barang_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
